# Generated by Django 3.2.3 on 2021-05-20 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210520_0445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avalable',
            new_name='is_available',
        ),
    ]
