# Generated by Django 3.2.3 on 2021-05-25 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_orderitem_shipping_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='shipping_duration',
            field=models.DurationField(default=datetime.timedelta(days=5)),
        ),
    ]
