# Generated by Django 3.2.3 on 2021-05-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_orderitem_shipping_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_duration',
        ),
    ]
