# Generated by Django 3.2.3 on 2021-05-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20210525_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, default='product/default.png', null=True, upload_to='product/'),
        ),
    ]
