# Generated by Django 3.2.3 on 2021-05-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_orderpayment_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='payment_method',
            field=models.CharField(default='COD', max_length=20),
        ),
    ]
