# Generated by Django 3.2.3 on 2021-05-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_orderpayment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='CODPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_number', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('expiration', models.DateTimeField()),
                ('order_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.orderpayment')),
            ],
        ),
    ]
