# Generated by Django 3.2.3 on 2021-05-31 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_cardpayment_codpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='codpayment',
            name='order_payment',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.orderpayment'),
            preserve_default=False,
        ),
    ]
