# Generated by Django 3.2.3 on 2021-05-31 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_codpayment_order_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='expiration',
            field=models.CharField(max_length=10),
        ),
    ]
